### ISSUE TITLE
arc radius 

### ISSUE THREAD

**Issue by hkashuri** [vpython/glowscript#145]
Hi ,
I am new to Vpython /python, and was trying to create a set of arcs with different radius. If the radius is declared inside extrusion it works , if it is declared outside it does not.
Thank you.

arclist = []
N=3
lamda = 3
        
for x in range(1,N,1):
    
    
    arcu=extrusion(path=paths.arc(angle1=-pi/4,angle2=pi/4),shape=[[shapes.circle(pos=[0,0,0],radius=1)]])
    #arcu=extrusion(path=paths.arc(angle1=-pi/4,angle2=pi/4,radius=x*lamda),shape=[[shapes.circle(pos=[0,0,0],radius=1)]])
    arcu.rotate(angle=pi/2, axis=vector(1,0,0), origin=vector(0,0,0))
    arcu.color = color.red
    arcu.pos=vector(x*lamda,0,0)
    arcu.index = x
    arcu.radius=x*lamda
    arclist.append( arcu )

**Comment by BruceSherwood** [comment]
This is because the properties you specify when creating an extrusion are used to create a "compound" object. After creating the compound you can only modify the properties of the compound. Here is the relevant text from the documentation for extrusions at 

   https://www.glowscript.org/docs/VPythonDocs/extrusion.html

An extrusion is made out of quads and triangles which are then made into a compound object for speed of display. You can make additional copies of an extrusion by cloning it. You can move an extrusion by specifying a new pos, and you can change its size, axis, up, color, opacity, shininess, and emissive, as with other objects. up controls the orientation of the initial cross section; default is vec(0,1,0); see the box object for a discussion of this attribute. Note that color is "multiplicative"; see compound.
