### ISSUE TITLE
f-string evaluation for Python 3

### ISSUE THREAD

**Issue by rodigu** [vpython/glowscript#157]
According to Python3 language specifications, function calls should be alowed with f-strings: https://www.python.org/dev/peps/pep-0498/

![SmartSelect_20211111-095917_Chrome.jpg](https://user-images.githubusercontent.com/58960796/141346551-cab857eb-7791-41f5-b76e-b33bb8c7df46.jpg)

However, the code:
```python
def sumAB(a, b):
    return a + b

print(f"sum 3 + 4: {sumAB(3,4)}")
```
Gives the error:
![SmartSelect_20211111-100122_Chrome.jpg](https://user-images.githubusercontent.com/58960796/141346961-8d9fe853-b3cd-46f9-aa24-15b527124e87.jpg)

The code:
```python
def sumAB(a, b):
    return a + b

result = sumAB(3,4)

print(f"sum 3 + 4: {result}")
```
Gives the expected output.

**Comment by BruceSherwood** [comment]
Thanks for this report. Support for f-strings in Web VPython is fairly recent, and evidently it isn't quite right. This is related to the complexity of inserting await in front of calls to user functions (because a user function might contain a waiting state such as rate). The strange-looking ~!# is associated with this machinery.

**Comment by BruceSherwood** [comment]
Now works correctly in Web VPython 3.2. Thanks much for the clear report.
